update adg luci

diff --git a/package/shenzt/luci-app-adguardhome-1/root/etc/init.d/AdGuardHome b/package/shenzt/luci-app-adguardhome-1/root/etc/init.d/AdGuardHome
--- a/package/shenzt/luci-app-adguardhome-1/root/etc/init.d/AdGuardHome
+++ b/package/shenzt/luci-app-adguardhome-1/root/etc/init.d/AdGuardHome
@@ -1,14 +1,16 @@
 #!/bin/sh /etc/rc.common
- 
+
 USE_PROCD=1
- 
+
 START=95
 STOP=01
 
 CONFIGURATION=AdGuardHome
 CRON_FILE=/etc/crontabs/root
-EXTRA_COMMANDS="do_redirect"
-EXTRA_HELP="        do_redirect 0 or 1"
+EXTRA_COMMANDS="do_redirect testbackup test_crontab"
+EXTRA_HELP="        do_redirect 0 or 1\
+        testbackup backup or restore\
+		test_crontab"
 set_forward_dnsmasq()
 {
 	local PORT="$1"
@@ -28,7 +30,7 @@ set_forward_dnsmasq()
 	done
 	uci delete dhcp.@dnsmasq[0].resolvfile 2>/dev/null
 	uci set dhcp.@dnsmasq[0].noresolv=1
-	uci commit dhcp 
+	uci commit dhcp
 	/etc/init.d/dnsmasq restart
 }
 
@@ -56,6 +58,14 @@ set_iptable()
 {
 	local ipv6_server=$1
 	local tcp_server=$2
+	uci -q batch <<-EOF >/dev/null 2>&1
+  delete firewall.AdGuardHome
+	set firewall.AdGuardHome=include
+	set firewall.AdGuardHome.type=script
+	set firewall.AdGuardHome.path=/usr/share/AdGuardHome/firewall.start
+	set firewall.AdGuardHome.reload=1
+	commit firewall
+EOF
 
 	IPS="`ifconfig | grep "inet addr" | grep -v ":127" | grep "Bcast" | awk '{print $2}' | awk -F : '{print $2}'`"
 	for IP in $IPS
@@ -83,6 +93,10 @@ set_iptable()
 
 clear_iptable()
 {
+	uci -q batch <<-EOF >/dev/null 2>&1
+  delete firewall.AdGuardHome
+	commit firewall
+EOF
 	local OLD_PORT="$1"
 	local ipv6_server=$2
 	IPS="`ifconfig | grep "inet addr" | grep -v ":127" | grep "Bcast" | awk '{print $2}' | awk -F : '{print $2}'`"
@@ -102,7 +116,7 @@ clear_iptable()
 		ip6tables -t nat -D PREROUTING -p udp -d $IP --dport 53 -j REDIRECT --to-ports $OLD_PORT >/dev/null 2>&1
 		ip6tables -t nat -D PREROUTING -p tcp -d $IP --dport 53 -j REDIRECT --to-ports $OLD_PORT >/dev/null 2>&1
 	done
-	
+
 }
 
 service_triggers() {
@@ -115,22 +129,22 @@ get_tz()
 	SET_TZ=""
 
 	if [ -e "/etc/localtime" ]; then
-		return 
+		return
 	fi
-	
+
 	for tzfile in /etc/TZ /var/etc/TZ
 	do
 		if [ ! -e "$tzfile" ]; then
 			continue
 		fi
-		
+
 		tz="`cat $tzfile 2>/dev/null`"
 	done
-	
+
 	if [ -z "$tz" ]; then
-		return  
+		return
 	fi
-	
+
 	SET_TZ=$tz
 }
 
@@ -174,7 +188,7 @@ use_port53()
 	/etc/init.d/dnsmasq reload
 }
 
-do_redirect() 
+do_redirect()
 {
 	config_load "${CONFIGURATION}"
 	local section="$CONFIGURATION"
@@ -196,10 +210,11 @@ do_redirect()
 	config_get "old_redirect" "$section" "old_redirect" "none"
 	config_get "old_port" "$section" "old_port" "0"
 	config_get "old_enabled" "$section" "old_enabled" "0"
+	uci get dhcp.@dnsmasq[0].port >/dev/null 2>&1 || uci set dhcp.@dnsmasq[0].port="53" >/dev/null 2>&1
 	if [ "$old_enabled" = "1" -a "$old_redirect" == "exchange" ]; then
 		AdGuardHome_PORT=$(uci get dhcp.@dnsmasq[0].port 2>/dev/null)
 	fi
-	
+
 	if [ "$old_redirect" != "$redirect" ] || [ "$old_port" != "$AdGuardHome_PORT" ] || [ "$old_enabled" = "1" -a "$enabled" = "0" ]; then
 		if [ "$old_redirect" != "none" ]; then
 			if [  "$old_redirect" == "redirect" -a "$old_port" != "0" ]; then
@@ -222,8 +237,7 @@ do_redirect()
 	uci add_list AdGuardHome.@AdGuardHome[0].old_port="$AdGuardHome_PORT" 2>/dev/null
 	uci add_list AdGuardHome.@AdGuardHome[0].old_enabled="$enabled" 2>/dev/null
 	uci commit AdGuardHome
-
-	[ "$enabled" -gt 0 ] || return 1
+	[ "$enabled" == "0" ] && return 1
 	if [ "$AdGuardHome_PORT" == "0" ]; then
 		return 1
 	fi
@@ -253,18 +267,18 @@ get_filesystem()
     }}}{
     split($0,d,"/");
     if ("/" in fs)
-    { 
+    {
     result1=fs["/"];
     }
     if ("/" in pt)
-    { 
+    {
     result2=pt["/"];
     }
     for (i=2;i<=length(d);i++)
     {
        p[i]=p[i-1]"/"d[i];
        if (p[i] in fs)
-        { 
+        {
         result1=fs[p[i]];
         result2=pt[p[i]];
         }
@@ -315,9 +329,51 @@ boot_service() {
 		fi
 	fi
 }
+testbackup(){
+	config_load "${CONFIGURATION}"
+	if [ "$1" == "backup" ]; then
+		backup
+	elif [ "$1" == "restore" ]; then
+		restore
+	fi
+}
+restore()
+{
+	config_get workdir $CONFIGURATION workdir "/usr/bin/AdGuardHome"
+	config_get backupwdpath $CONFIGURATION backupwdpath "/usr/bin/AdGuardHome"
+	cp -u -r -f $backupwdpath/data $workdir
+}
+backup() {
+	config_get backupwdpath $CONFIGURATION backupwdpath "/usr/bin/AdGuardHome"
+	mkdir -p $backupwdpath/data
+	config_get workdir $CONFIGURATION workdir "/usr/bin/AdGuardHome"
+	config_get backupfile $CONFIGURATION backupfile ""
+	for one in $backupfile;
+	do
+		while :
+		do
+			if [ -d "$backupwdpath/data/$one" ]; then
+				cpret=$(cp -u -r -f $workdir/data/$one $backupwdpath/data 2>&1)
+			else
+				cpret=$(cp -u -r -f $workdir/data/$one $backupwdpath/data/$one 2>&1)
+			fi
+			echo "$cpret"
+			echo "$cpret" | grep "no space left on device"
+			if [ "$?" == "0" ]; then
+				echo "磁盘已满,删除log重试中"
+				del_querylog && continue
+				rm -f -r $backupwdpath/data/filters
+				rm -f -r $workdir/data/filters && continue
+				echo "backup failed"
+			fi
+			break
+		done
+	done
+}
 start_service() {
 	# Reading config
 	config_load "${CONFIGURATION}"
+	# update password
 	config_get hashpass $CONFIGURATION hashpass ""
 	if [ -n "$hashpass" ]; then
 		config_editor "users.password" "$hashpass" "$configpath"
@@ -325,52 +381,21 @@ start_service() {
 	fi
 	local enabled
 	config_get_bool enabled $CONFIGURATION enabled 0
-	
-	if [ "$enabled" == "1" ]; then
-	local ADDITIONAL_ARGS=""
-	config_get configpath $CONFIGURATION configpath "/etc/AdGuardHome.yaml"
-	config_get binpath $CONFIGURATION binpath "/usr/bin/AdGuardHome/AdGuardHome"
-	
-	echo -e "$configpath\n$binpath">/lib/upgrade/keep.d/luci-app-adguardhome
-	mkdir -p ${binpath%/*}
-	ADDITIONAL_ARGS="$ADDITIONAL_ARGS -c $configpath"
-	
-	config_get httpport $CONFIGURATION httpport 3000
-	ADDITIONAL_ARGS="$ADDITIONAL_ARGS -p $httpport"
-	
-	config_get workdir $CONFIGURATION workdir "/usr/bin/AdGuardHome"
-	ADDITIONAL_ARGS="$ADDITIONAL_ARGS -w $workdir"
-	config_get backupwd $CONFIGURATION backupwd "0"
-	if [ "$backupwd" == "1" ] && [ ! -d "$workdir/data" ]; then
-		config_get backupwdpath $CONFIGURATION backupwdpath "/usr/bin/AdGuardHome"
-		cp -r -f $backupwdpath/data $workdir
-	fi
-	mkdir -p $workdir/data
-	echo -e "$configpath\n$binpath">/lib/upgrade/keep.d/luci-app-adguardhome
-	# hack to save config file when upgrade system
-	config_get keepdb $CONFIGURATION keepdb 0
-	if [ "$keepdb" -eq 1 ]; then
-		echo -e "$workdir/data/sessions.db\n$workdir/data/stats.db\n$workdir/data/querylog.json">>/lib/upgrade/keep.d/luci-app-adguardhome
-	fi
-	config_get logfile $CONFIGURATION logfile ""
-	if [ -n "$logfile" ]; then
-		ADDITIONAL_ARGS="$ADDITIONAL_ARGS -l $logfile"
-	fi
-	
-	if [ ! -f "$binpath" ]; then
+	# update crontab
+	do_crontab
+	if [ "$enabled" == "0" ]; then
+		procd_kill $CONFIGURATION
 		do_redirect 0
-		rm /var/run/update_core_error 2>/dev/null
-		touch /var/run/update_core
-		sh /usr/share/AdGuardHome/update_core.sh 2>&1 >/tmp/AdGuardHome_update.log || touch /var/run/update_core_error
-		rm /var/run/update_core
-		exit 0
-	fi 
-
-	config_get_bool verbose $CONFIGURATION verbose 0
-	if [ "$verbose" -eq 1 ]; then
-		ADDITIONAL_ARGS="$ADDITIONAL_ARGS -v"
+		return
 	fi
-	
+	#what need to do before reload
+	config_get workdir $CONFIGURATION workdir "/usr/bin/AdGuardHome"
+
+	config_get backupfile $CONFIGURATION backupfile ""
+	mkdir -p $workdir/data
+	if [ -n "$backupfile" ] && [ ! -d "$workdir/data" ]; then
+		restore
+	fi
 	# for overlay data-stk-oo not suppport
 	local cwdfs=$(get_filesystem $workdir)
 	echo "workdir is a $cwdfs filesystem"
@@ -388,15 +413,50 @@ start_service() {
 		ln -s /tmp/sessions.db $workdir/data/sessions.db 2>/dev/null
 		fi
 	fi
+	local ADDITIONAL_ARGS=""
+	config_get configpath $CONFIGURATION configpath "/etc/AdGuardHome.yaml"
+	config_get binpath $CONFIGURATION binpath "/usr/bin/AdGuardHome/AdGuardHome"
+
+	echo -e "$configpath\n$binpath">/lib/upgrade/keep.d/luci-app-adguardhome
+	mkdir -p ${binpath%/*}
+	ADDITIONAL_ARGS="$ADDITIONAL_ARGS -c $configpath"
+	ADDITIONAL_ARGS="$ADDITIONAL_ARGS -w $workdir"
+	config_get httpport $CONFIGURATION httpport 3000
+	ADDITIONAL_ARGS="$ADDITIONAL_ARGS -p $httpport"
+
+	echo -e "$configpath\n$binpath">/lib/upgrade/keep.d/luci-app-adguardhome
+	# hack to save config file when upgrade system
+	config_get keepdb $CONFIGURATION keepdb 0
+	if [ "$keepdb" -eq 1 ]; then
+		echo -e "$workdir/data/sessions.db\n$workdir/data/stats.db\n$workdir/data/querylog.json">>/lib/upgrade/keep.d/luci-app-adguardhome
+	fi
+	config_get logfile $CONFIGURATION logfile ""
+	if [ -n "$logfile" ]; then
+		ADDITIONAL_ARGS="$ADDITIONAL_ARGS -l $logfile"
+	fi
+
+	if [ ! -f "$binpath" ]; then
+		do_redirect 0
+		rm /var/run/update_core_error 2>/dev/null
+		touch /var/run/update_core
+		sh /usr/share/AdGuardHome/update_core.sh 2>&1 >/tmp/AdGuardHome_update.log || touch /var/run/update_core_error
+		rm /var/run/update_core
+		exit 0
+	fi
+
+	config_get_bool verbose $CONFIGURATION verbose 0
+	if [ "$verbose" -eq 1 ]; then
+		ADDITIONAL_ARGS="$ADDITIONAL_ARGS -v"
+	fi
+
 	procd_open_instance
 	get_tz
-	if [ -n "$SET_TZ" ]; then 
-		procd_set_param env TZ="$SET_TZ" 
+	if [ -n "$SET_TZ" ]; then
+		procd_set_param env TZ="$SET_TZ"
 	fi
 	procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-5}
 	procd_set_param limits core="unlimited"
-	procd_set_param stderr 1 
-	# pass config to script on start
+	procd_set_param stderr 1
 	procd_set_param command $binpath $ADDITIONAL_ARGS
 	procd_set_param file "$configpath"
 	procd_set_param file "/etc/config/AdGuardHome"
@@ -413,30 +473,14 @@ start_service() {
 			echo "no config start watching"
 		fi
 	fi
-	do_crontab
 	echo "AdGuardHome turn on"
 	(sleep 10 && [ -z "$(pgrep $binpath)" ] && logger "AdGuardHome" "no process in 10s cancel redirect" && do_redirect 0 )&
-	fi
 }
 reload_service()
 {
-	config_load "${CONFIGURATION}"
+	rm /var/run/AdGucitest >/dev/null 2>&1
 	echo "AdGuardHome reloading"
-	config_get_bool enabled $CONFIGURATION enabled 0
-	if [ "$enabled" == "0" ]; then
-		procd_kill $CONFIGURATION
-		do_redirect 0
-		do_crontab
-		config_get hashpass $CONFIGURATION hashpass ""
-		if [ -n "$hashpass" ]; then
-			config_editor "users.password" "$hashpass" "$configpath"
-			uci set $CONFIGURATION.$CONFIGURATION.hashpass=""
-		fi
-	else
-		procd_send_signal $CONFIGURATION
-		start
-	fi
-	echo "enabled=$enabled"
+	start
 }
 
 del_querylog(){
@@ -449,7 +493,7 @@ if [ "$btarget"x == "$wtarget"x ]; then
 	return 0
 fi
 if [ "$btarget" \> "$wtarget" ]; then
-	rm -f $backupwdpath/data/$btarget 
+	rm -f $backupwdpath/data/$btarget
 	return 0
 else
 	rm -f $workdir/data/$wtarget
@@ -461,24 +505,9 @@ stop_service()
 	config_load "${CONFIGURATION}"
 	do_redirect 0
 	do_crontab
-	config_get backupwd $CONFIGURATION backupwd "0"
-	if [ "$backupwd" == "1" ]; then
-		config_get backupwdpath $CONFIGURATION backupwdpath "/usr/bin/AdGuardHome"
-		config_get workdir $CONFIGURATION workdir "/usr/bin/AdGuardHome"
-		while :
-		do
-			cpret=$(cp -r -f $workdir/data $backupwdpath 2>&1)
-			echo "$cpret"
-			echo "$cpret" | grep "no space left on device"
-			if [ "$?" == "0" ]; then
-				echo "磁盘已满,删除log重试中"
-				del_querylog && continue
-				rm -f -r $backupwdpath/data/filters
-				rm -f -r $workdir/data/filters && continue
-				echo "backup failed"
-			fi
-			break
-		done
+	config_get backupfile $CONFIGURATION backupfile "0"
+	if [ -n "$backupfile" ]; then
+		backup
 	fi
 	echo "AdGuardHome turn off"
 	echo "enabled=$enabled"
@@ -489,20 +518,58 @@ boot() {
 		service_started
 	fi
 }
+test_crontab(){
+config_load "${CONFIGURATION}"
+do_crontab
+}
 do_crontab(){
-	config_get autoupdate $CONFIGURATION autoupdate "0"
-	grep "/usr/share/AdGuardHome/update_core.sh"  $CRON_FILE
-	if [ "$?" == "0" ]; then
-		if [ $autoupdate -eq 1 ]; then
+	config_get crontab $CONFIGURATION crontab ""
+	local findstr default cronenable
+	local cronreload=0
+	findstr="/usr/share/AdGuardHome/update_core.sh"
+	default="#30 3 * * * /usr/share/AdGuardHome/update_core.sh 2>&1"
+	[ "$enabled" == "0" ] || [ "${crontab//autoupdate/}" == "$crontab" ] && cronenable=0 || cronenable=1
+	crontab_editor
+
+	findstr="tail -n [0-9]* .*/data/querylog.json > .*/data/querylog.json"
+	default="#0 * * * * tail -n 2000 $workdir/data/querylog.json > $workdir/data/querylog.json"
+	[ "$enabled" == "0" ] || [ "${crontab//cutquerylog/}" == "$crontab" ] && cronenable=0 || cronenable=1
+	crontab_editor
+
+	config_get logfile $CONFIGURATION logfile ""
+	findstr="tail -n [0-9]* $logfile > $logfile"
+	default="#30 3 * * * tail -n 2000 $logfile > $logfile"
+	[ "$logfile" == "syslog" ] || [ "$logfile" == "" ] || [ "$enabled" == "0" ] || [ "${crontab//cutruntimelog/}" == "$crontab" ] && cronenable=0 || cronenable=1
+	crontab_editor
+
+	findstr="/usr/share/AdGuardHome/addhost.sh"
+	default="#0 * * * * /usr/share/AdGuardHome/addhost.sh"
+	[ "$enabled" == "0" ] || [ "${crontab//autohost/}" == "$crontab" ] && cronenable=0 || cronenable=1
+	crontab_editor
+	[ "$cronenable" == "0" ] && /usr/share/AdGuardHome/addhost.sh "del" "noreload" || /usr/share/AdGuardHome/addhost.sh "" "noreload"
+
+	findstr="/usr/share/AdGuardHome/gfw2adg.sh"
+	default="#30 3 * * * /usr/share/AdGuardHome/gfw2adg.sh"
+	[ "$enabled" == "0" ] || [ "${crontab//autogfw/}" == "$crontab" ] && cronenable=0 || cronenable=1
+	crontab_editor
+	[ "$cronreload" -gt 0 ] && /etc/init.d/cron restart
+}
+crontab_editor(){
+	local line="$(grep "$findstr" $CRON_FILE)"
+	if [ -n "$line" -a "${line:0:1}" != "#" ]; then
+		if [ $cronenable -eq 1 ]; then
 			return
 		else
-			sed -i '/\/usr\/share\/AdGuardHome\/update_core.sh/d' $CRON_FILE
-			/etc/init.d/cron restart
+			sed -i "\,$findstr,d" $CRON_FILE
+			echo "#$line" >> $CRON_FILE
+			cronreload=$((cronreload+1))
 		fi
 	else
-		if [ $autoupdate -eq 1 ]; then
-			echo '30 3 * * * /usr/share/AdGuardHome/update_core.sh 2>&1' >> $CRON_FILE
-			/etc/init.d/cron restart
+		if [ $cronenable -eq 1 ]; then
+			[ -z "$line" ] && line="$default"
+			sed -i "\,$findstr,d" $CRON_FILE
+			echo "${line:1}" >> $CRON_FILE
+			cronreload=$((cronreload+1))
 		else
 			return
 		fi
